/// Raw English word list for the game content database.
/// Format per entry:  word|emoji   prefixes:  * = very common word,  ! = irregular (not fully decodable)
/// Features and difficulty are computed automatically (see en_features.dart) — no hand-assigned levels.
const enWordData = <String>[
  // animals
  'cat|🐱', 'dog|🐶', 'pig|🐷', 'hen|🐔', 'fox|🦊', 'bat|🦇', 'rat|🐀', 'cow|🐄', 'ant|🐜', 'bee|🐝',
  'owl|🦉', 'yak|🐃', 'ox|🐂', 'fish|🐟', 'frog|🐸', 'duck|🦆', 'crab|🦀', 'snail|🐌', 'snake|🐍', 'sheep|🐑',
  'goat|🐐', 'horse|🐴', 'mouse|🐭', 'bird|🐦', 'shark|🦈', 'whale|🐳', 'seal|🦭', 'deer|🦌', 'bear|🐻', 'lion|🦁',
  'tiger|🐯', 'zebra|🦓', 'camel|🐫', 'llama|🦙', 'koala|🐨', 'panda|🐼', 'monkey|🐒', 'rabbit|🐰', 'turtle|🐢', 'parrot|🦜',
  'spider|🕷️', 'penguin|🐧', 'dolphin|🐬', 'giraffe|🦒', 'elephant|🐘', 'octopus|🐙', 'butterfly|🦋', 'kangaroo|🦘',
  'crocodile|🐊', 'dinosaur|🦖', 'hamster|🐹', 'squirrel|🐿️', 'peacock|🦚', 'flamingo|🦩', 'lobster|🦞', 'squid|🦑',
  'wolf|🐺', 'swan|🦢', 'eagle|🦅', 'caterpillar|🐛', 'grasshopper|🦗', 'hippopotamus|🦛', 'rhinoceros|🦏', 'gorilla|🦍',
  'chick|🐤', 'unicorn|🦄', 'dragon|🐉', 'ladybug|🐞', 'beetle|🪲', 'worm|🪱', 'puppy', 'kitten', 'lamb', 'pony', 'duckling',
  // food
  'egg|🥚', 'nut|🥜', 'bun', 'jam', 'bread|🍞', 'cake|🎂', 'corn|🌽', 'rice|🍚', 'milk|🥛', 'pie|🥧', 'tea|🍵',
  'apple|🍎', 'pear|🍐', 'grapes|🍇', 'lemon|🍋', 'melon|🍈', 'mango|🥭', 'peach|🍑', 'cherry|🍒', 'banana|🍌',
  'carrot|🥕', 'potato|🥔', 'tomato|🍅', 'onion|🧅', 'garlic|🧄', 'pizza|🍕', 'burger|🍔', 'sandwich|🥪', 'cookie|🍪',
  'candy|🍬', 'honey|🍯', 'cheese|🧀', 'butter|🧈', 'noodles|🍜', 'soup|🍲', 'salad|🥗', 'popcorn|🍿', 'donut|🍩',
  'waffle|🧇', 'pretzel|🥨', 'pancake|🥞', 'coconut|🥥', 'pineapple|🍍', 'strawberry|🍓', 'watermelon|🍉',
  'broccoli|🥦', 'cucumber|🥒', 'avocado|🥑', 'chocolate|🍫', 'juice|🧃', 'jelly', 'muffin', 'toast',
  // objects and places
  'hat|🎩', 'cap|🧢', 'bag|👜', 'box|📦', 'pen|🖊️', 'cup|🥤', 'mug|☕', 'bed|🛏️', 'map|🗺️', 'key|🔑', 'bell|🔔',
  'ball|⚽', 'kite|🪁', 'drum|🥁', 'lamp|💡', 'sock|🧦', 'shoe|👟', 'boot|👢', 'coat|🧥', 'dress|👗', 'ring|💍',
  'clock|⏰', 'watch|⌚', 'phone|📱', 'book|📖', 'brush|🖌️', 'chair|🪑', 'door|🚪', 'bus|🚌', 'car|🚗', 'van|🚐',
  'ship|🚢', 'boat|⛵', 'truck|🚚', 'train|🚂', 'bike|🚲', 'rocket|🚀', 'tent|⛺', 'house|🏠', 'tooth|🦷', 'hand|✋',
  'foot|🦶', 'nose|👃', 'ear|👂', 'crown|👑', 'gift|🎁', 'flag|🚩', 'star|⭐', 'moon|🌙', 'sun|☀️', 'cloud|☁️',
  'rain|🌧️', 'snow|❄️', 'tree|🌳', 'leaf|🍃', 'rose|🌹', 'plant|🌱', 'shell|🐚', 'rock|🪨', 'fire|🔥', 'web|🕸️',
  'net|🥅', 'axe|🪓', 'magnet|🧲', 'ladder|🪜', 'basket|🧺', 'candle|🕯️', 'pencil|✏️', 'crayon|🖍️', 'scissors|✂️',
  'umbrella|☂️', 'guitar|🎸', 'violin|🎻', 'trumpet|🎺', 'robot|🤖', 'rainbow|🌈', 'balloon|🎈', 'castle|🏰',
  'window|🪟', 'button|🔘', 'garden|🌷', 'planet|🪐', 'computer|💻', 'camera|📷', 'ticket|🎟️', 'gloves|🧤',
  'teddy|🧸', 'ruler|📏', 'trophy|🏆', 'medal|🏅', 'hammer|🔨', 'wrench|🔧', 'bucket|🪣', 'bottle|🍼', 'airplane|✈️',
  'jet', 'sled|🛷', 'skate|⛸️', 'mask|🎭', 'globe|🌍', 'bridge|🌉', 'tractor|🚜', 'ambulance|🚑', 'helicopter|🚁',
  'volcano|🌋', 'island|🏝️', 'mountain|⛰️', 'desert|🏜️', 'school|🏫', 'hospital|🏥', 'dice|🎲', 'puzzle|🧩',
  'feather|🪶', 'bone|🦴', 'egg', 'pot', 'pan|🍳', 'bowl|🥣', 'fork', 'spoon|🥄', 'knife|🔪', 'drop|💧', 'wave|🌊',
  'heart|❤️', 'sword|🗡️', 'shield|🛡️', 'anchor|⚓', 'compass|🧭', 'lantern|🏮', 'tablet', 'pillow', 'blanket',
  // short decodable words (no picture)
  'sat', 'mat', 'pat', 'tap', 'tip', 'pin', 'pit', 'sit', 'nap', 'pan', 'tan', 'man', 'can', 'dad', 'mad', 'had',
  'dig', 'big', 'wig', 'log', 'hog', 'got', 'hot', 'not', 'lot', 'top', 'mop', 'hop', 'cot', 'kid', 'kit', 'kin',
  'red', 'bed', 'led', 'set', 'get', 'wet', 'pet', 'jet', 'ten', 'men', 'hen', 'leg', 'peg', 'beg',
  'run', 'fun', 'gun', 'sun', 'mud', 'bud', 'rug', 'hug', 'bug', 'mug', 'tub', 'cub', 'rub', 'hum', 'gum',
  'yes', 'zip', 'fix', 'mix', 'six', 'box', 'wax', 'quiz', 'quit', 'vet', 'yell', 'hill', 'fill', 'doll', 'mess', 'kiss', 'buzz', 'puff',
  'shop', 'shed', 'shut', 'chip', 'chop', 'chin', 'rich', 'much', 'thin', 'thick', 'path', 'bath', 'moth', 'math',
  'king', 'sing', 'wing', 'long', 'song', 'hang', 'back', 'neck', 'pick', 'lock', 'duck', 'luck', 'kick',
  'stop', 'spot', 'step', 'skip', 'slip', 'flag', 'flip', 'glad', 'plan', 'clap', 'club', 'drip', 'grab', 'trip',
  'swim', 'spin', 'snap', 'brag', 'crisp', 'jump', 'lamp', 'camp', 'milk', 'help', 'belt', 'gift', 'list', 'nest', 'best',
  'hand', 'sand', 'pond', 'tent', 'went', 'bump', 'dusk', 'desk', 'mask', 'frost', 'trunk', 'stamp', 'blend', 'twist',
  // vowel patterns
  'make', 'take', 'came', 'game', 'name', 'same', 'time', 'ride', 'hide', 'like', 'home', 'rope', 'note', 'hole',
  'cube', 'tube', 'cute', 'mule', 'gate', 'plate', 'smile', 'stone', 'flute', 'shine', 'shape', 'slide',
  'paint', 'wait', 'tail', 'mail', 'day', 'stay', 'may', 'play', 'say', 'pray', 'gray',
  'green', 'sleep', 'feet', 'keep', 'week', 'seed', 'bean', 'read', 'sea', 'team', 'meat', 'beach', 'dream',
  'road', 'soap', 'coat', 'toad', 'boat', 'goal', 'snow', 'grow', 'show', 'slow', 'blow',
  'light', 'night', 'right', 'high', 'fight', 'bright', 'find', 'kind', 'mind', 'wild', 'cold', 'gold', 'told', 'old',
  'look', 'good', 'wood', 'cook', 'foot', 'hook', 'food', 'room', 'zoo', 'cool', 'pool', 'roof', 'boot',
  'out', 'shout', 'loud', 'round', 'sound', 'found', 'mouth', 'now', 'how', 'down', 'brown', 'town', 'clown', 'growl',
  'oil', 'coin', 'boil', 'soil', 'point', 'boy', 'toy', 'joy', 'enjoy',
  'park', 'farm', 'dark', 'hard', 'card', 'shark', 'for', 'born', 'horn', 'short', 'sport', 'storm', 'fork',
  'her', 'fern', 'girl', 'first', 'shirt', 'turn', 'burn', 'hurt', 'nurse', 'purple', 'curl',
  'new', 'blew', 'flew', 'grew', 'chew', 'blue', 'glue', 'true', 'saw', 'paw', 'draw', 'straw', 'claw', 'tie', 'lie',
  'phone', 'photo', 'graph', 'when', 'which', 'while', 'white', 'knee', 'knock', 'know', 'write', 'wrong', 'wrap',
  'catch', 'match', 'watch', 'kitchen', 'bridge', 'edge', 'badge', 'lamb', 'thumb', 'climb',
  // two+ syllables
  'bubble', 'puddle', 'little', 'table', 'simple', 'jungle', 'happy', 'sunny', 'funny', 'baby', 'lady', 'party',
  'tiny', 'yellow', 'follow', 'shadow', 'morning', 'evening', 'yesterday', 'tomorrow', 'together', 'beautiful',
  'wonderful', 'adventure', 'important', 'different', 'children', 'animal', 'family', 'number', 'remember',
  'interesting', 'library', 'telescope', 'vegetable', 'picnic', 'sunset', 'cupcake', 'football', 'sandpit',
  'bedtime', 'goldfish', 'starfish', 'snowman', 'treetop', 'rainy', 'windy', 'teacher', 'farmer', 'sister',
  'brother', 'mother', 'father', 'thunder', 'lightning', 'paper', 'tiger', 'robin', 'music', 'student',
  'birthday', 'holiday', 'elephant', 'banana', 'potato', 'adventure', 'fantastic', 'magnificent', 'invisible',
  'electricity', 'imagination', 'celebration', 'information', 'transportation',
  // high-frequency / irregular sight words
  '*!the', '*and', '*!was', '*!said', '*!you', '*!they', '*!have', '*!come', '*!some', '*!one', '*!two', '*!of', '*!to',
  '*!do', '*!are', '*!were', '*what', '*!where', '*!who', '*!there', '*!their', '*!could', '*!would', '*!should',
  '*!because', '*!friend', '*!people', '*!again', '*!water', '*!any', '*!many', '*!does', '*!goes', '*!put', '*!push',
  '*!pull', '*!give', '*!live', '*!love', '*!done', '*!gone', '*!once', '*!laugh', '*!eight', '*!sure', '*!buy',
  '*it', '*is', '*in', '*at', '*on', '*up', '*can', '*not', '*big', '*run', '*see', '*go', '*we', '*me', '*he', '*she',
  '*my', '*by', '*no', '*so', '*look', '*like', '*play', '*with', '*this', '*that', '*then', '*them', '*from', '*have',
  '*will', '*went', '*little', '*good', '*day', '*down', '*out', '*all', '*make', '*take', '*here', '*come', '*about',
  '*after', '*every', '*before', '*very', '*over', '*under', '*open', '*please', '*thank', '*also',
  // longer words for upper steps
  'astronaut', 'binoculars', 'calendar', 'dictionary', 'encyclopedia', 'fascinating', 'grandmother', 'grandfather',
  'harmonica', 'independent', 'jellyfish', 'kindergarten', 'lemonade', 'marvellous', 'neighbourhood', 'orchestra',
  'parachute', 'quarrelsome', 'restaurant', 'submarine', 'thermometer', 'unbelievable', 'vocabulary', 'waterfall',
  'xylophone', 'zookeeper', 'adventurous', 'butterflies', 'complicated', 'discovery', 'environment',
  'fireworks', 'gigantic', 'hurricane', 'invention', 'journey', 'knowledge', 'lighthouse', 'microscope', 'nightingale',
  'opportunity', 'photograph', 'question', 'rectangle', 'spaghetti', 'triangle', 'underground', 'vacation',
  'whispering', 'explanation', 'mysterious', 'treasure', 'measure', 'pleasure', 'creature', 'nature', 'picture',
  'station', 'mention', 'caution', 'lotion', 'fraction', 'direction', 'attention', 'collection', 'competition',
];
